version: '2'
# ************ README ****************
# Reads env vars from .env
# Requires docker-compose version 1.7+
# ************************************

services:
<%- include('container-configs/nginx.yml', {docker}); %>

<% if(docker.mysql) { %>
<%- include('container-configs/mysql.yml', {docker}); %>
<% } %>

<% if(docker.redis) { %>
<%- include('container-configs/redis.yml', {docker}); %>
<% } %>

<% if(docker.queue) { %>
<%- include('container-configs/queue.yml', {docker}); %>
<% } %>

networks:
  <%= docker.name %>-network:
    driver: bridge